import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import request from 'supertest';
import app from '../src/app';
import { prisma } from '../src/utils/prismaClient';

describe('AccessGuard Integration Flows', () => {
  const uniqueId = Date.now();
  const testEmail = `integration-test-${uniqueId}@example.com`;
  const testPassword = 'Password123!';
  let authCookies: string[] = [];

  beforeAll(async () => {
    // Clean up any potential lingering test email
    await prisma.task.deleteMany({
      where: { user: { email: testEmail } }
    });
    await prisma.user.deleteMany({
      where: { email: testEmail }
    });
  });

  afterAll(async () => {
    // Delete database records generated by this run to keep environment clean
    await prisma.task.deleteMany({
      where: { user: { email: testEmail } }
    });
    await prisma.user.deleteMany({
      where: { email: testEmail }
    });
    await prisma.$disconnect();
  });

  it('1. Register new user successfully -> status code 201', async () => {
    const response = await request(app)
      .post('/api/v1/auth/register')
      .send({
        email: testEmail,
        password: testPassword,
        role: 'USER',
      });

    expect(response.status).toBe(201);
    expect(response.body).toHaveProperty('status', 'success');
    expect(response.body.data.user).toHaveProperty('email', testEmail);
    expect(response.body.data.user).not.toHaveProperty('password');
  });

  it('2. Login user -> retrieves token and sets HttpOnly cookies', async () => {
    const response = await request(app)
      .post('/api/v1/auth/login')
      .send({
        email: testEmail,
        password: testPassword,
      });

    expect(response.status).toBe(200);
    expect(response.body).toHaveProperty('status', 'success');
    expect(response.body).toHaveProperty('token'); // Backup token in body
    expect(response.body.data.user).toHaveProperty('email', testEmail);

    // Save the set-cookie headers to authenticate subsequent calls
    authCookies = response.headers['set-cookie'] || [];
    expect(authCookies.length).toBeGreaterThanOrEqual(1);

    // Assert that the cookie name matches 'token' or 'refreshToken'
    const containsTokenCookie = authCookies.some(c => c.startsWith('token=') || c.startsWith('refreshToken='));
    expect(containsTokenCookie).toBe(true);
  });

  it('3. Create a task using authentication cookies -> status code 201', async () => {
    const response = await request(app)
      .post('/api/v1/tasks')
      .set('Cookie', authCookies)
      .send({
        title: 'Complete Integration Testing',
        description: 'Verify end-to-end user journeys in access control contexts',
        status: 'IN_PROGRESS',
      });

    expect(response.status).toBe(201);
    expect(response.body).toHaveProperty('id');
    expect(response.body).toHaveProperty('title', 'Complete Integration Testing');
    expect(response.body).toHaveProperty('status', 'IN_PROGRESS');
  });

  it('4. Retrieve and verify the created task -> status code 200', async () => {
    const response = await request(app)
      .get('/api/v1/tasks')
      .set('Cookie', authCookies);

    expect(response.status).toBe(200);
    expect(Array.isArray(response.body)).toBe(true);
    
    // Find the task we created in the listing
    const targetTask = response.body.find((t: any) => t.title === 'Complete Integration Testing');
    expect(targetTask).toBeDefined();
    expect(targetTask.description).toBe('Verify end-to-end user journeys in access control contexts');
    expect(targetTask.status).toBe('IN_PROGRESS');
  });
});
